# view the title of the pane in the top of the pane
set -g pane-border-status top
#set -g pane-border-format " [ ###P #T ] "

# by default add current path to pane title
set-hook -g after-split-window 'selectp -T ""'
set-hook -g after-new-window 'selectp -T ""'
set-hook -g after-new-session 'selectp -T ""'
set -g pane-border-format " [ ###{pane_index} #{?pane_title,#{pane_title},#{pane_current_path}} ] "

# change tmux prefix to Ctrl+a
set-option -g prefix C-a
bind-key C-a send-prefix

# enable mouse
set -g mouse on

# switch panes using Alt-arrow without prefix
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

# open new window splits (panes) in the same directory
bind '"' split-window -v -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
# open new windows in the same directory
bind c   new-window   -c "#{pane_current_path}"

# increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# fix colors
set -g default-terminal "tmux-256color"

# pane divider
#set-window-option -g pane-border-style fg=colour11,bg=colour234
set-window-option -g pane-border-style "default"
set-window-option -g pane-active-border-style fg=colour118
#set-window-option -g pane-active-border-style fg=colour118,bg=colour240

# start windows and panes index at 1, instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# highlight current window in status bar
setw -g window-status-current-format "#[reverse] #I:#W"

# dim inactive pane
set -g window-style fg=default,bg=colour235
set -g window-active-style fg=default,bg=black
#set -g window-style 'fg=default,bg=default'
#set -g window-active-style 'fg=default,bg=default'

