# view the title of the pane in the top of the pane
set -g pane-border-status top

# by default add current path to pane title
set-hook -g after-split-window 'selectp -T ""'
set-hook -g after-new-window 'selectp -T ""'
set-hook -g after-new-session 'selectp -T ""'
set -g pane-border-format " [ ###{pane_index} #{?pane_title,#{pane_title},#{pane_current_path}} ] "

# change tmux prefix to Ctrl+a
set-option -g prefix C-a
bind-key C-a send-prefix

# enable mouse
set -g mouse on

# switch panes using Alt-arrow without prefix
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

# open new window splits (panes) in the same directory
bind '"' split-window -v -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
# open new windows in the same directory
bind  c  new-window      -c "#{pane_current_path}"

# reload tmux configuration 
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# switch theme by pressing C-a -> h -> l (light theme) or C-a -> h -> d (dark theme)
bind-key h switch-client -T theme_table
bind-key -T theme_table l source-file ~/.tmux/light-theme.conf
bind-key -T theme_table d source-file ~/.tmux/dark-theme.conf

# increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# start windows and panes index at 1, instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# highlight current window in status bar
setw -g window-status-current-format "#[reverse] #I:#W"

# fix colors
set -g default-terminal "tmux-256color"

# by default enable dark theme
source-file ~/.tmux/dark-theme.conf
# source-file ~/.tmux/light-theme.conf
