# Light theme for tmux

# pane divider
set-window-option -g pane-border-style fg=default,bg=colour251
set-window-option -g pane-active-border-style fg=default,bg=default

# dim inactive pane
set -g window-style fg=default,bg=colour253
set -g window-active-style fg=default,bg=colour231
